def rm_mf(txt:str):
    """Function for removing movie versions"""
    return (
        txt.strip()
        .replace('(arabisk/bosnisk/engelsk/tysk/kurdisk/svensk tale, norsk tekst)', '')
        .replace('25th anniversary show from royal albert hall - direkte ove', '')
        .replace('ekstraforestilling fred. 09.sept. kl. 22.00.', '')
        .replace('25th anniversary show from royal albert hall', '')
        .replace('ekstraforestilling sund. 11.sept. kl.20.00.', '')
        .replace('daybreakers(utekstet originalversjon)', '')
        .replace('norsk actionthriller. alder 15 år.', '')
        .replace('50th anniversary celebration atmos', '')
        .replace('(nb! filmen er tatt over av fox)', '')
        .replace('(nb! gratis! - kun kjøp i døra)', '')
        .replace('première!  norsk.  alder: 9 år.', '')
        .replace('(3d - briller kjøpes i kiosken)', '')
        .replace('gratis - ingen forhåndsbest.', '')
        .replace('briller (25,kjøpes i kiosk)', '')
        .replace('(2\x1f\x1f\x1fd,norsk tale)', '')
        .replace('(nyrestaurert/digitalisert)', '')
        .replace('2011 jubileumsforestilling', '')
        .replace('i3d(orginal) full rulle', '')
        .replace('(månedens joker nr. 2!)', '')
        .replace('(festivalpass gjelder)', '')
        .replace('(nb! eneste visning!)', '')
        .replace('med regissørbesøk', '')
        .replace('stord filmklubb', '')
        .replace(':knøttenefilmen', '')
        .replace('(bø filmklubb)', '')
        .replace('10-årsjubileum', '')
        .replace('(gammel reg.)', '')
        .replace('stor ståhai)', '')
        .replace('halvmaraton', '')
        .replace('direkte ove', '')
        .replace('(1978)', '')
        .replace('83d)', '')
        .replace('(n)', '')
        .replace('org.versj stor ståhai', '')
        .replace('ekstraforestilling', '')
        .replace('og valgfritt tale', '')
        .replace('ikke billettsalg', '')
        .replace('30-års jubileum', '')
        .replace('direkteoverført', '')
        .replace('forest. kl.1400', '')
        .replace('originalversjon', '')
        .replace('verdenspremiere', '')
        .replace('forf. innleder', '')
        .replace('i atmos 3d lyd', '')
        .replace('ikke book tale', '')
        .replace('månedens joker', '')
        .replace('norgespremiere', '')
        .replace('orginalversjon', '')
        .replace('usikker lengde', '')
        .replace('barnehagekino', '')
        .replace('gratisvisning', '')
        .replace('norgespremier', '')
        .replace('originalspråk', '')
        .replace('forestilling', '')
        .replace('dolby atmos', '')
        .replace('førpremiere', '')
        .replace('horrornight', '')
        .replace('ingen tekst', '')
        .replace('nederlandsk', '')
        .replace('originalutg', '')
        .replace('portugisisk', '')
        .replace('sing- along', '')
        .replace('sing-a-long', '')
        .replace('strikkekino', '')
        .replace('.vises i 3d', '')
        .replace('gratiskino', '')
        .replace('indonesisk', '')
        .replace('norgesprem', '')
        .replace('uten tekst', '')
        .replace('seniorkino', '')
        .replace('sing-along', '')
        .replace('bollywood', '')
        .replace('eng tekst', '')
        .replace('filmdager', '')
        .replace('filmklubb', '')
        .replace('italiensk', '')
        .replace('med norsk', '')
        .replace('med tekst', '')
        .replace('nei tekst', '')
        .replace('subtitles', '')
        .replace('trehundre', '')
        .replace('utektstet', '')
        .replace('babykino', '')
        .replace('extended', '')
        .replace('islandsk', '')
        .replace('litauisk', '')
        .replace('original', '')
        .replace('premiere', '')
        .replace('utekstet', '')
        .replace('17. mai', '')
        .replace('blueray', '')
        .replace('digital', '')
        .replace('engelsk', '')
        .replace('forest.', '')
        .replace('japansk', '')
        .replace('med nor', '')
        .replace('n-prem.', '')
        .replace('preview', '')
        .replace('reprise', '')
        .replace('stemmer', '')
        .replace('tekster', '')
        .replace('tekstet', '')
        .replace('u/tekst', '')
        .replace('versjon', '')
        .replace('version', '')
        .replace('2\x1fd', '')
        .replace('3\x1fd', '')
        .replace('17 mai', '')
        .replace('dubbet', '')
        .replace('fransk', '')
        .replace('gratis', '')
        .replace('m. eng', '')
        .replace('m/ no.', '')
        .replace('n.tale', '')
        .replace('n-prem', '')
        .replace('norske', '')
        .replace('polish', '')
        .replace('polske', '')
        .replace('samisk', '')
        .replace('spansk', '')
        .replace('tale-a', '')
        .replace('teksta', '')
        .replace('35 mm', '')
        .replace('atmos', '')
        .replace('dansk', '')
        .replace('dubba', '')
        .replace('hindi', '')
        .replace('m .no', '')
        .replace('norsk', '')
        .replace('og 2d', '')
        .replace('og 3d', '')
        .replace('polsk', '')
        .replace('tekst', '')
        .replace('versj', '')
        .replace('35mm', '')
        .replace('dig.', '')
        .replace('dubb', '')
        .replace('eng.', '')
        .replace('film', '')
        .replace('i 2d', '')
        .replace('i 3d', '')
        .replace('imax', '')
        .replace('m.no', '')
        .replace('org.', '')
        .replace('orig', '')
        .replace('tale', '')
        .replace('tysk', '')
        .replace('); r', '')
        .replace('2 d', '')
        .replace('3 d', '')
        .replace('4dx', '')
        .replace('5.1', '')
        .replace('dub', '')
        .replace('dvd', '')
        .replace('hfr', '')
        .replace('no.', '')
        .replace('org', '')
        .replace('txt', '')
        .replace('2d, no', '')
        .replace('3d, no', '')
        .replace('2d, n', '')
        .replace('3d, n', '')
        .replace('2d no', '')
        .replace('3d no', '')
        .replace('2d', '')
        .replace('3d', '')
        .replace('4k', '')
        .replace('m/', '')
        .replace('u/', '')
        .replace('*', '')
        .replace('!', '')
        .replace('+', '')
        .replace('.', ' ')
        .replace('/', ' ')
        .replace('-', ' ')
        .replace('"', '')
        .replace(':', ' ')
        .replace(';', ' ')
        .replace(',', ' ')
        .replace('(', '')
        .replace(')', '')
        .replace("'", '')
        .replace('  ', ' ')
        .strip()
    )
